// Generated by CoffeeScript 1.6.3
module.exports = function(server) {
  var Article, Navigation, io;
  io = require('socket.io').listen(server);
  Article = require('../models/article');
  Navigation = require('../models/navigation');
  io.sockets.on('connection', function(socket) {
    return socket.on('observe', function(msg) {
      switch (msg.collection) {
        case "articles":
          console.log("1x");
          return Article.all(function(err, articles) {
            console.log(articles.map(function(article) {
              return article.id;
            }));
            if (err != null) {
              return;
            }
            return articles.forEach(function(article) {
              console.log(article.id);
              return socket.emit('articles', article.toJSON());
            });
          });
        case "navigations":
          return Navigation.all(function(err, navigations) {
            if (err != null) {
              return;
            }
            return navigations.forEach(function(navigation) {
              return socket.emit('navigations', navigation.toJSON());
            });
          });
      }
    });
  });
  return io;
};
