// Generated by CoffeeScript 1.6.3
var DB, Model, RecordNotFound, pluralize, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

pluralize = require('pluralize');

DB = require("../../db/db");

RecordNotFound = (function(_super) {
  __extends(RecordNotFound, _super);

  function RecordNotFound() {
    _ref = RecordNotFound.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  return RecordNotFound;

})(Error);

Model = (function() {
  Model.RecordNotFound = RecordNotFound;

  Model.className = 'Model';

  Model.db = new DB();

  Model.prototype.changedAttributes = [];

  Model.prototype.isNewRecord = true;

  Model.tableName = function() {
    return pluralize(this.className.toLowerCase());
  };

  Model.fields = function(callback) {
    var _this = this;
    if (this._fields != null) {
      if (callback != null) {
        callback.call(this, null, this._fields);
      }
      return this._fields;
    }
    return this.db.loadFieldsFor(this.tableName(), function(err, fields) {
      if (err != null) {
        callback.call(_this, err);
        return;
      }
      _this._fields = fields;
      if (callback != null) {
        return callback.call(_this, null, fields);
      }
    });
  };

  Model.klass = function() {
    return this;
  };

  Model.all = function(callback) {
    var records,
      _this = this;
    records = [];
    this.db.loadAllFor(this.tableName(), function(err, rows) {
      var record, _i, _len;
      if (err != null) {
        return callback.call(_this, err);
      }
      for (_i = 0, _len = rows.length; _i < _len; _i++) {
        record = rows[_i];
        records.push(new _this(record));
      }
      return callback.call(_this, null, records);
    });
    return records;
  };

  Model.find = function(id, callback) {
    var model,
      _this = this;
    model = new this;
    this.db.findById(id, this.tableName(), function(err, row) {
      var key, value;
      if (err != null) {
        return callback.call(_this, err);
      }
      if (row == null) {
        return callback.call(_this, new _this.RecordNotFound("Record with id " + id + " not found"));
      }
      _this.isNewRecord = false;
      for (key in row) {
        value = row[key];
        model.set(key, value);
      }
      model.changedAttributes = [];
      return callback.call(_this, null);
    });
    return model;
  };

  function Model(options) {
    var key, option;
    if (options == null) {
      options = {};
    }
    this.defineProperties();
    for (key in options) {
      option = options[key];
      this[key] = option;
    }
    this;
  }

  Model.prototype.save = function(callback) {
    var field, saveCallback, values, _i, _len, _ref1,
      _this = this;
    saveCallback = function(err, row) {
      var changedFields, field, value;
      if (err != null) {
        callback.call(_this, err);
      }
      changedFields = [];
      for (field in row) {
        value = row[field];
        _this.set(field, value);
        changedFields.push(field);
      }
      _this.changedAttributes = [];
      return callback.call(_this, null, changedFields);
    };
    values = [];
    _ref1 = this.changedAttributes;
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      field = _ref1[_i];
      values.push(this.get(field));
    }
    if (this.isNewRecord) {
      return this.constructor.db.insertRow(this.constructor.tableName(), this.changedAttributes, values, saveCallback);
    } else {
      return this.constructor.db.updateRow(this.constructor.tableName(), this.id, this.changedAttributes, values, saveCallback);
    }
  };

  Model.prototype.get = function(field) {
    return this["_" + field] || null;
  };

  Model.prototype.set = function(field, value) {
    if (this.changedAttributes.indexOf(field) === -1 && this["_" + field] !== value) {
      this.changedAttributes.push(field);
    }
    return this["_" + field] = value;
  };

  Model.prototype.defineProperties = function() {
    var _this = this;
    return this.constructor.fields(function(err, fields) {
      return fields.forEach(function(field) {
        return Object.defineProperty(_this, field, {
          get: function() {
            return _this.get(field);
          },
          set: function(value) {
            return _this.set(field, value);
          },
          enumerable: true
        });
      });
    });
  };

  return Model;

})();

Model.fields();

module.exports = Model;
